[package]
name = "thumbhash_rs"
version = "0.1.0"
edition = "2024"
description = "Fast ThumbHash bindings for Python using Rust (PyO3)"
documentation = "https://github.com/fdemmer/thumbhash-rs#readme"
homepage = "https://github.com/fdemmer/thumbhash-rs"
repository = "https://github.com/fdemmer/thumbhash-rs"
license = "MIT"

[lib]
name = "_thumbhash"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module"] }
fast-thumbhash = "0.2"
