def rgba_to_thumb_hash(width: int, height: int, rgba: bytes) -> bytes: ...
def thumb_hash_to_rgba(hash: bytes) -> tuple[int, int, bytes]: ...
def thumb_hash_to_average_rgba(hash: bytes) -> tuple[float, float, float, float]: ...
def thumb_hash_to_approximate_aspect_ratio(hash: bytes) -> float: ...
